// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAdmin = "admin"

// Admin mapped from table <admin>
type Admin struct {
	LoginName string `gorm:"column:login_name;type:varchar" json:"login_name"`
	Password  string `gorm:"column:password;type:varchar" json:"password"`
}

// TableName Admin's table name
func (*Admin) TableName() string {
	return TableNameAdmin
}
