// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
)

func Use(db *gorm.DB) *Query {
	return &Query{
		db:           db,
		Admin:        newAdmin(db),
		ErrorCode:    newErrorCode(db),
		FromToConfig: newFromToConfig(db),
		I18n:         newI18n(db),
		Lang:         newLang(db),
	}
}

type Query struct {
	db *gorm.DB

	Admin        admin
	ErrorCode    errorCode
	FromToConfig fromToConfig
	I18n         i18n
	Lang         lang
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:           db,
		Admin:        q.Admin.clone(db),
		ErrorCode:    q.ErrorCode.clone(db),
		FromToConfig: q.FromToConfig.clone(db),
		I18n:         q.I18n.clone(db),
		Lang:         q.Lang.clone(db),
	}
}

type queryCtx struct {
	Admin        *adminDo
	ErrorCode    *errorCodeDo
	FromToConfig *fromToConfigDo
	I18n         *i18nDo
	Lang         *langDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Admin:        q.Admin.WithContext(ctx),
		ErrorCode:    q.ErrorCode.WithContext(ctx),
		FromToConfig: q.FromToConfig.WithContext(ctx),
		I18n:         q.I18n.WithContext(ctx),
		Lang:         q.Lang.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	return &QueryTx{q.clone(q.db.Begin(opts...))}
}

type QueryTx struct{ *Query }

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
